-- ============================================================================
-- CRM PRODUCTION DATABASE BLUEPRINT
-- Target DBMS : PostgreSQL 15+
-- Author role : Enterprise Architect / Senior DB Engineer
-- Notes       : Assumes a single-tenant deployment. For multi-tenant SaaS,
--               add tenant_id to every table + row-level security policies
--               (flagged inline where relevant, not implemented here).
-- ============================================================================


-- ============================================================================
-- SECTION 0: SCHEMA SETUP
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS crm;
SET search_path TO crm, public;

-- Extensions used:
--   pgcrypto -> for gen_random_uuid() if you later want UUID public IDs
--   citext   -> case-insensitive email comparisons without app-layer LOWER()
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;


-- ============================================================================
-- SECTION 1: COMPREHENSIVE DDL
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABLE: teams
-- Design notes:
--   - manager_id references users, but users references teams -> circular FK.
--     Solved by creating teams WITHOUT the manager_id FK constraint here,
--     then adding it via ALTER TABLE after users exists (see bottom of §1).
-- ----------------------------------------------------------------------------
CREATE TABLE crm.teams (
    team_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name    VARCHAR(120) NOT NULL,
    manager_id   BIGINT,                          -- FK added later
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_teams_team_name UNIQUE (team_name)
);
COMMENT ON TABLE crm.teams IS 'Sales teams / territories used for ownership and reporting rollups.';

-- ----------------------------------------------------------------------------
-- TABLE: users  (internal staff, not customer contacts)
-- ----------------------------------------------------------------------------
CREATE TABLE crm.users (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR(80)  NOT NULL,
    last_name      VARCHAR(80)  NOT NULL,
    email          CITEXT       NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(20)  NOT NULL DEFAULT 'sales_rep',
    team_id        BIGINT,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('admin', 'manager', 'sales_rep')),
    CONSTRAINT fk_users_team FOREIGN KEY (team_id)
        REFERENCES crm.teams (team_id) ON DELETE SET NULL ON UPDATE CASCADE
);
COMMENT ON TABLE crm.users IS 'Internal staff accounts (admins, managers, reps).';

-- Now that users exists, close the loop on teams.manager_id
ALTER TABLE crm.teams
    ADD CONSTRAINT fk_teams_manager FOREIGN KEY (manager_id)
        REFERENCES crm.users (user_id) ON DELETE SET NULL ON UPDATE CASCADE;

-- ----------------------------------------------------------------------------
-- TABLE: accounts  (companies / organizations)
-- ----------------------------------------------------------------------------
CREATE TABLE crm.accounts (
    account_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name     VARCHAR(150) NOT NULL,
    industry         VARCHAR(80),
    website          VARCHAR(255),
    phone            VARCHAR(30),
    billing_address  TEXT,
    owner_id         BIGINT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_accounts_owner FOREIGN KEY (owner_id)
        REFERENCES crm.users (user_id) ON DELETE SET NULL ON UPDATE CASCADE
);
COMMENT ON TABLE crm.accounts IS 'Customer organizations. owner_id = rep with primary account responsibility.';

-- ----------------------------------------------------------------------------
-- TABLE: contacts  (individual people, optionally tied to an account)
-- ----------------------------------------------------------------------------
CREATE TABLE crm.contacts (
    contact_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT,                        -- nullable: standalone individuals allowed
    first_name   VARCHAR(80)  NOT NULL,
    last_name    VARCHAR(80)  NOT NULL,
    email        CITEXT,
    phone        VARCHAR(30),
    job_title    VARCHAR(100),
    owner_id     BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_contacts_account FOREIGN KEY (account_id)
        REFERENCES crm.accounts (account_id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_contacts_owner FOREIGN KEY (owner_id)
        REFERENCES crm.users (user_id) ON DELETE SET NULL ON UPDATE CASCADE
);
COMMENT ON TABLE crm.contacts IS 'Individual people. account_id nullable to support contacts with no company.';

-- Partial unique index: enforce email uniqueness only when email IS NOT NULL
-- (a plain UNIQUE constraint already treats multiple NULLs as distinct in
-- Postgres, but this is explicit and documents the intent clearly).
CREATE UNIQUE INDEX uq_contacts_email ON crm.contacts (email) WHERE email IS NOT NULL;

-- ----------------------------------------------------------------------------
-- TABLE: leads  (unqualified prospects, pre-conversion)
-- ----------------------------------------------------------------------------
CREATE TABLE crm.leads (
    lead_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name            VARCHAR(80) NOT NULL,
    last_name             VARCHAR(80) NOT NULL,
    email                 CITEXT,
    phone                 VARCHAR(30),
    company_name          VARCHAR(150),
    lead_source           VARCHAR(50),
    status                VARCHAR(20) NOT NULL DEFAULT 'new',
    owner_id              BIGINT,
    converted_contact_id  BIGINT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_leads_status CHECK (
        status IN ('new', 'contacted', 'qualified', 'converted', 'disqualified')
    ),
    CONSTRAINT fk_leads_owner FOREIGN KEY (owner_id)
        REFERENCES crm.users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_leads_converted_contact FOREIGN KEY (converted_contact_id)
        REFERENCES crm.contacts (contact_id) ON DELETE SET NULL ON UPDATE CASCADE,
    -- A lead can only reference a converted contact once it IS converted.
    CONSTRAINT ck_leads_conversion_consistency CHECK (
        (status = 'converted' AND converted_contact_id IS NOT NULL)
        OR (status <> 'converted')
    )
);
COMMENT ON TABLE crm.leads IS 'Pre-qualification prospects. Converts into a contacts row.';

-- ----------------------------------------------------------------------------
-- TABLE: opportunities  (deals in the pipeline)
-- ----------------------------------------------------------------------------
CREATE TABLE crm.opportunities (
    opportunity_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT NOT NULL,
    contact_id      BIGINT,
    owner_id        BIGINT,
    name            VARCHAR(150) NOT NULL,
    stage           VARCHAR(20) NOT NULL DEFAULT 'prospecting',
    amount          NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
    close_date      DATE,
    probability     SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_opportunities_stage CHECK (
        stage IN ('prospecting', 'qualification', 'proposal', 'negotiation', 'won', 'lost')
    ),
    CONSTRAINT ck_opportunities_probability CHECK (probability BETWEEN 0 AND 100),
    -- Business decision: RESTRICT, not CASCADE. Revenue records must never
    -- disappear silently because someone deleted an account row.
    CONSTRAINT fk_opportunities_account FOREIGN KEY (account_id)
        REFERENCES crm.accounts (account_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_opportunities_contact FOREIGN KEY (contact_id)
        REFERENCES crm.contacts (contact_id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_opportunities_owner FOREIGN KEY (owner_id)
        REFERENCES crm.users (user_id) ON DELETE SET NULL ON UPDATE CASCADE
);
COMMENT ON TABLE crm.opportunities IS 'Active/closed deals. account_id mandatory; contact_id optional.';

-- ----------------------------------------------------------------------------
-- TABLE: products
-- ----------------------------------------------------------------------------
CREATE TABLE crm.products (
    product_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(150) NOT NULL,
    price        NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    description  TEXT,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_products_name UNIQUE (name)
);

-- ----------------------------------------------------------------------------
-- TABLE: opportunity_products  (junction: many-to-many, opportunities <-> products)
-- ----------------------------------------------------------------------------
CREATE TABLE crm.opportunity_products (
    opportunity_id  BIGINT NOT NULL,
    product_id      BIGINT NOT NULL,
    quantity        INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price      NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    PRIMARY KEY (opportunity_id, product_id),
    CONSTRAINT fk_oppprod_opportunity FOREIGN KEY (opportunity_id)
        REFERENCES crm.opportunities (opportunity_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_oppprod_product FOREIGN KEY (product_id)
        REFERENCES crm.products (product_id) ON DELETE RESTRICT ON UPDATE CASCADE
);
COMMENT ON TABLE crm.opportunity_products IS 'Line items per deal. unit_price is a snapshot, not a live FK to products.price (see §3).';

-- ----------------------------------------------------------------------------
-- TABLE: activities  (calls, emails, meetings, tasks, notes)
-- Design notes:
--   Instead of a generic (related_to_type, related_to_id) polymorphic pair,
--   this uses 4 nullable typed FKs + a CHECK ensuring exactly one is set.
--   Trade-off: wider table, but real FK integrity is preserved and the
--   query planner can use normal FK-backed indexes instead of a composite
--   type+id lookup with no referential guarantee.
-- ----------------------------------------------------------------------------
CREATE TABLE crm.activities (
    activity_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(20) NOT NULL,
    subject         VARCHAR(200) NOT NULL,
    description     TEXT,
    due_date        TIMESTAMPTZ,
    status          VARCHAR(20) NOT NULL DEFAULT 'pending',
    owner_id        BIGINT,
    contact_id      BIGINT,
    account_id      BIGINT,
    opportunity_id  BIGINT,
    lead_id         BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_activities_type CHECK (
        type IN ('call', 'email', 'meeting', 'task', 'note')
    ),
    CONSTRAINT ck_activities_status CHECK (
        status IN ('pending', 'completed', 'cancelled')
    ),
    -- Exactly one parent entity must be set (polymorphic-safe, FK-enforced)
    CONSTRAINT ck_activities_single_parent CHECK (
        num_nonnulls(contact_id, account_id, opportunity_id, lead_id) = 1
    ),
    CONSTRAINT fk_activities_owner FOREIGN KEY (owner_id)
        REFERENCES crm.users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_activities_contact FOREIGN KEY (contact_id)
        REFERENCES crm.contacts (contact_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_activities_account FOREIGN KEY (account_id)
        REFERENCES crm.accounts (account_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_activities_opportunity FOREIGN KEY (opportunity_id)
        REFERENCES crm.opportunities (opportunity_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_activities_lead FOREIGN KEY (lead_id)
        REFERENCES crm.leads (lead_id) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMENT ON TABLE crm.activities IS 'Interaction log. Exactly one of contact_id/account_id/opportunity_id/lead_id is populated per row.';


-- ============================================================================
-- SECTION 2: INDEXING & OPTIMIZATION STRATEGY
-- ============================================================================

-- --- Foreign key columns: Postgres does NOT auto-index FK columns (unlike
--     the PK side). Every FK used in JOINs below gets an index.

CREATE INDEX idx_users_team_id            ON crm.users (team_id);
CREATE INDEX idx_accounts_owner_id        ON crm.accounts (owner_id);
CREATE INDEX idx_contacts_account_id      ON crm.contacts (account_id);
CREATE INDEX idx_contacts_owner_id        ON crm.contacts (owner_id);
CREATE INDEX idx_leads_owner_id           ON crm.leads (owner_id);
CREATE INDEX idx_opportunities_account_id ON crm.opportunities (account_id);
CREATE INDEX idx_opportunities_contact_id ON crm.opportunities (contact_id);

-- --- Composite index: the single most common query pattern in any CRM is
--     "this rep's open deals sorted by close date" -> a rep-scoped pipeline
--     view. Leading column = owner_id (equality filter, high selectivity
--     per rep), second column = stage (equality filter), third = close_date
--     (range/sort). This satisfies the left-prefix rule for queries filtering
--     on owner_id alone, owner_id+stage, or all three.
CREATE INDEX idx_opportunities_owner_stage_close
    ON crm.opportunities (owner_id, stage, close_date);

-- --- Partial index: "open pipeline" dashboards never care about won/lost
--     deals, but that's most of the historical table over time. A partial
--     index keeps it small and fast instead of indexing dead-weight rows.
CREATE INDEX idx_opportunities_open_pipeline
    ON crm.opportunities (close_date)
    WHERE stage NOT IN ('won', 'lost');

-- --- Activities: the timeline view for any single record ("show me all
--     activity on this contact") is the highest-traffic activities query.
--     Each parent FK gets its own index; a single composite wouldn't help
--     since only one column is ever non-null per row.
CREATE INDEX idx_activities_contact_id     ON crm.activities (contact_id)     WHERE contact_id IS NOT NULL;
CREATE INDEX idx_activities_account_id     ON crm.activities (account_id)     WHERE account_id IS NOT NULL;
CREATE INDEX idx_activities_opportunity_id ON crm.activities (opportunity_id) WHERE opportunity_id IS NOT NULL;
CREATE INDEX idx_activities_lead_id        ON crm.activities (lead_id)        WHERE lead_id IS NOT NULL;

-- --- Composite: "my open tasks, due soonest first" is the rep's daily
--     landing screen. owner_id equality + status equality + due_date sort.
CREATE INDEX idx_activities_owner_status_due
    ON crm.activities (owner_id, status, due_date);

-- --- Search: name/company lookups are near-universal in CRM UIs. Plain
--     btree on last_name covers prefix search; for real fuzzy/typeahead
--     search, add pg_trgm + a GIN trigram index instead (mentioned, not
--     built here, since it depends on actual search UX requirements).
CREATE INDEX idx_contacts_last_name  ON crm.contacts (last_name);
CREATE INDEX idx_accounts_name       ON crm.accounts (account_name);

-- --- Junction table: PK (opportunity_id, product_id) already covers
--     "products on this deal" lookups. Add the reverse direction for
--     "which deals include this product" (e.g. product performance reports).
CREATE INDEX idx_oppprod_product_id ON crm.opportunity_products (product_id);

-- --- Partitioning consideration:
--     At CRM scale (roughly >10-20M activities/opportunities rows, or
--     multi-year retention requirements), consider RANGE partitioning
--     `activities` and `opportunities` by created_at (monthly or yearly).
--     This keeps indexes small, makes archival/purge trivial (DROP a
--     partition instead of a DELETE), and most CRM reads are already
--     time-scoped ("this quarter's deals"). Not implemented here since it's
--     only worth the operational overhead once actual row-count/retention
--     numbers justify it -- premature partitioning adds maintenance cost
--     for no benefit on a young dataset.


-- ============================================================================
-- SECTION 3: NORMALIZATION & DENORMALIZATION REVIEW
-- ============================================================================

-- 3NF audit:
--   1. contacts.account_id -> accounts.account_name is NOT stored redundantly
--      on contacts. Good: no transitive dependency, no update anomaly risk.
--   2. opportunities.amount is a candidate concern: if opportunity_products
--      line items exist, amount could theoretically be SUM(quantity * unit_price).
--      Storing both creates a transitive-dependency-like risk (amount can
--      drift out of sync with its line items).
--        -> DELIBERATE DENORMALIZATION, not an oversight. Reasoning: amount
--           is a forecast/commit figure a rep sets directly and may differ
--           from a literal line-item sum (discounts, bundling, verbal
--           adjustments). Treat opportunities.amount as the system of
--           record for pipeline reporting; treat opportunity_products as
--           supporting detail, not the derivation source. Do NOT auto-sync
--           via trigger unless product-line pricing is your actual deal
--           value driver -- confirm this with the business before building it.
--   3. opportunity_products.unit_price duplicates products.price at time of
--      sale. This is CORRECT denormalization, not a violation: it's a
--      point-in-time snapshot. If products.price changes next quarter,
--      historical deals must NOT retroactively reprice. This is the audit-
--      trail case where write safety (immutable history) outranks strict
--      normalization.
--   4. leads vs contacts duplication (first_name, last_name, email, phone
--      appear in both tables) looks like a 3NF smell but is intentional:
--      leads and contacts have different lifecycles and validation rules
--      (a lead is unqualified/unverified data; a contact is a trusted
--      record). Merging them into one table with a status flag is possible
--      but complicates every downstream FK (opportunities, activities would
--      need to tolerate "contact" rows that are actually just leads).
--      Recommendation: keep them separate; the lead_id -> converted_contact_id
--      link already gives you full lineage without merging the tables.
--   5. Read-path denormalization NOT yet built here, but recommended once
--      you have real traffic: a materialized view for the pipeline
--      dashboard (SUM(amount) BY stage BY owner BY month), refreshed on a
--      schedule (or on opportunity write via trigger if near-real-time is
--      required). Don't compute that aggregate live against the OLTP tables
--      once activity volume grows -- it'll compete with write traffic.

-- Practical balance for this schema:
--   - Keep transactional tables (accounts/contacts/opportunities/activities)
--     strictly normalized -- these are write-heavy and correctness-critical.
--   - Denormalize only at the reporting/read layer (materialized views,
--     summary tables) rather than inside the OLTP schema itself. This keeps
--     the source of truth clean while still giving dashboards fast reads.


-- ============================================================================
-- SECTION 4: MOCK DATA & VALIDATION
-- ============================================================================

-- Deterministic seed data using explicit IDs (GENERATED BY DEFAULT AS
-- IDENTITY permits this, unlike GENERATED ALWAYS).

INSERT INTO crm.teams (team_id, team_name) VALUES
    (1, 'Enterprise Sales'),
    (2, 'SMB Sales');

INSERT INTO crm.users (user_id, first_name, last_name, email, password_hash, role, team_id) VALUES
    (1, 'Amara',  'Uwase',   'amara.uwase@example.com',  'hash1', 'manager',   1),
    (2, 'Eric',   'Nshuti',  'eric.nshuti@example.com',  'hash2', 'sales_rep', 1),
    (3, 'Diane',  'Mukiza',  'diane.mukiza@example.com', 'hash3', 'sales_rep', 2);

UPDATE crm.teams SET manager_id = 1 WHERE team_id = 1;
UPDATE crm.teams SET manager_id = 1 WHERE team_id = 2;

INSERT INTO crm.accounts (account_id, account_name, industry, owner_id) VALUES
    (1, 'Kivu Logistics',   'Transportation', 2),
    (2, 'Rwanda AgriTech',  'Agriculture',     3);

INSERT INTO crm.contacts (contact_id, account_id, first_name, last_name, email, owner_id) VALUES
    (1, 1, 'Jean',  'Habimana', 'jean.habimana@kivulogistics.com', 2),
    (2, 2, 'Grace', 'Ingabire', 'grace.ingabire@rwandaagritech.com', 3);

INSERT INTO crm.leads (lead_id, first_name, last_name, email, company_name, lead_source, status, owner_id) VALUES
    (1, 'Paul', 'Kagabo', 'paul.kagabo@newlead.com', 'Kagabo Traders', 'website', 'new', 2);

INSERT INTO crm.products (product_id, name, price) VALUES
    (1, 'CRM Starter License', 500.00),
    (2, 'CRM Pro License',     1200.00);

INSERT INTO crm.opportunities (opportunity_id, account_id, contact_id, owner_id, name, stage, amount, close_date, probability) VALUES
    (1, 1, 1, 2, 'Kivu Logistics - Pro Rollout', 'proposal',    3600.00, '2026-09-15', 60),
    (2, 2, 2, 3, 'AgriTech - Starter Pilot',      'negotiation', 1500.00, '2026-08-01', 75);

INSERT INTO crm.opportunity_products (opportunity_id, product_id, quantity, unit_price) VALUES
    (1, 2, 3, 1200.00),
    (2, 1, 3, 500.00);

INSERT INTO crm.activities (activity_id, type, subject, status, owner_id, opportunity_id) VALUES
    (1, 'call',    'Discovery call',      'completed', 2, 1),
    (2, 'meeting', 'Contract walkthrough','pending',   2, 1),
    (3, 'email',   'Pricing follow-up',   'completed', 3, 2);


-- ----------------------------------------------------------------------------
-- VERIFICATION QUERY
-- Demonstrates: INNER JOIN (opportunities->accounts, ->users),
--               LEFT JOIN (activities, since not every deal has one yet),
--               aggregate window function (running rank of deal size
--               within each owner's book, plus a per-owner total via
--               window SUM).
-- ----------------------------------------------------------------------------
SELECT
    o.opportunity_id,
    o.name                                  AS deal_name,
    a.account_name,
    u.first_name || ' ' || u.last_name      AS owner_name,
    o.stage,
    o.amount,
    COUNT(act.activity_id)                  AS activity_count,
    RANK() OVER (
        PARTITION BY o.owner_id
        ORDER BY o.amount DESC
    )                                        AS deal_rank_in_owner_book,
    SUM(o.amount) OVER (
        PARTITION BY o.owner_id
    )                                        AS owner_total_pipeline
FROM crm.opportunities o
INNER JOIN crm.accounts a ON a.account_id = o.account_id
INNER JOIN crm.users u    ON u.user_id    = o.owner_id
LEFT JOIN crm.activities act ON act.opportunity_id = o.opportunity_id
GROUP BY
    o.opportunity_id, o.name, a.account_name, u.first_name, u.last_name,
    o.stage, o.amount, o.owner_id
ORDER BY o.owner_id, deal_rank_in_owner_book;

-- Expected result shape (2 rows given the seed data above):
-- opportunity_id | deal_name                     | account_name    | owner_name   | stage        | amount  | activity_count | deal_rank_in_owner_book | owner_total_pipeline
-- 1              | Kivu Logistics - Pro Rollout  | Kivu Logistics  | Eric Nshuti  | proposal     | 3600.00 | 2              | 1                       | 3600.00
-- 2              | AgriTech - Starter Pilot      | Rwanda AgriTech | Diane Mukiza | negotiation  | 1500.00 | 1              | 1                       | 1500.00
